### ISSUE TITLE
Ignore when a user reconnects within the 5 minute delay

### ISSUE THREAD

**Issue by itsrachelfish** [cephers/mumbot#1]
Kate disconnected and reconnected twice within a minute and the bot output two messages spaced out 5 minutes apart. I think it would make sense if we simply ignored reconnections within the 5 minute delay between notifications.

![image](https://user-images.githubusercontent.com/1670549/226805475-b3603235-f238-4084-b55b-eb408d5b3b73.png)

![image](https://user-images.githubusercontent.com/1670549/226805509-6097d7d4-ced3-4c93-874a-7041e6093e8d.png)

**Comment by cephers** [comment]
bf5549817c7705700ac03a5bd653e2a0977b3263
